plugins {
    id 'com.android.test'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.liquidglassexample.macrobenchmark'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk 24
        targetSdk rootProject.ext.targetSdkVersion
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        benchmark {
            debuggable = true
            matchingFallbacks = ['release']
            signingConfig = signingConfigs.debug
        }
    }

    targetProjectPath = ':app'
    experimentalProperties['android.experimental.self-instrumenting'] = true
}

dependencies {
    implementation 'androidx.test.ext:junit:1.2.1'
    implementation 'androidx.test:runner:1.6.2'
    implementation 'androidx.test.uiautomator:uiautomator:2.3.0'
    implementation 'androidx.benchmark:benchmark-macro-junit4:1.3.4'
}

androidComponents {
    beforeVariants(selector().all()) { variantBuilder ->
        variantBuilder.enable = variantBuilder.buildType == 'benchmark'
    }
}
